# Generated by Django 4.2.5 on 2023-09-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterToo', '0003_rename_last_post_date_profile_last_active_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follow',
            new_name='follows',
        ),
    ]
