# Generated by Django 4.2.5 on 2023-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterToo', '0005_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_offensive',
            field=models.BooleanField(default=False),
        ),
    ]
